//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.ui
{ 

public sealed partial class TbUI
{
    private readonly Dictionary<string, ui.UIInfo> _dataMap;
    private readonly List<ui.UIInfo> _dataList;
    
    public TbUI(JSONNode _json)
    {
        _dataMap = new Dictionary<string, ui.UIInfo>();
        _dataList = new List<ui.UIInfo>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = ui.UIInfo.DeserializeUIInfo(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, ui.UIInfo> DataMap => _dataMap;
    public List<ui.UIInfo> DataList => _dataList;

    public ui.UIInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ui.UIInfo Get(string key) => _dataMap[key];
    public ui.UIInfo this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}