//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.ui
{ 

public sealed partial class UIInfo :  Bright.Config.BeanBase 
{
    public UIInfo(JSONNode _json) 
    {
        { if(!_json["id"].IsString) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  Desc = _json["desc"]; }
        { if(!_json["layer"].IsNumber) { throw new SerializationException(); }  Layer = _json["layer"]; }
        PostInit();
    }

    public UIInfo(string id, string desc, int layer ) 
    {
        this.Id = id;
        this.Desc = desc;
        this.Layer = layer;
        PostInit();
    }

    public static UIInfo DeserializeUIInfo(JSONNode _json)
    {
        return new ui.UIInfo(_json);
    }

    public string Id { get; private set; }
    public string Desc { get; private set; }
    public int Layer { get; private set; }

    public const int __ID__ = 1966359036;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Desc:" + Desc + ","
        + "Layer:" + Layer + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
