//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public ui.TbUI TbUI {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbUI = new ui.TbUI(loader("ui_tbui")); 
        tables.Add("ui.TbUI", TbUI);
        PostInit();

        TbUI.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbUI.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}