//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.bonus
{ 

public sealed partial class DropInfo :  Bright.Config.BeanBase 
{
    public DropInfo(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  Desc = _json["desc"]; }
        PostInit();
    }

    public DropInfo(int id, string desc ) 
    {
        this.Id = id;
        this.Desc = desc;
        PostInit();
    }

    public static DropInfo DeserializeDropInfo(JSONNode _json)
    {
        return new bonus.DropInfo(_json);
    }

    public int Id { get; private set; }
    public string Desc { get; private set; }

    public const int __ID__ = -2014781108;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Desc:" + Desc + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
